# Mark Shust's Docker Configuration for Magento
# (https://github.com/markshust/docker-magento)
#
# Version 36.0.1

version: "3"

services:
  app:
    image: markoshust/magento-nginx:1.18-4
    ports:
      - "80:8000"
      - "443:8443"
    links:
      - db
      - phpfpm
    volumes: &appvolumes
      - ~/.composer:/var/www/.composer:cached
      - appdata:/var/www/html
      - sockdata:/sock
      - ssldata:/etc/nginx/certs

  phpfpm:
    image: markoshust/magento-php:7.4-fpm-3
    links:
      - db
    env_file: env/develop.env
    volumes: *appvolumes

  db:
    image: percona:5.7
    command: --max_allowed_packet=64M
    ports:
      - "3306:3306"
    env_file: env/develop.env
    volumes:
      - dbdata:/var/lib/mysql

  elasticsearch:
    image: markoshust/magento-elasticsearch:7.7.1-0
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - "discovery.type=single-node"


volumes:
  appdata:
  dbdata:
  sockdata:
  ssldata:
