name: ci
on:
  pull_request:
  push:
    branches:
      - "master"

jobs:
  run:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: ['ubuntu-latest']
        php-versions: ['7.4']
        magento: ['2.4.0', '2.4.1', '2.4.2', '2.4.3']
        coveralls: [ false ]
        include:
          - operating-system: 'ubuntu-latest'
            php-versions: '8.1'
            magento: '2.4.4'
            coveralls: false
          - operating-system: 'ubuntu-latest'
            php-versions: '8.1'
            magento: '2.4.5'
            coveralls: true
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Configure PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          tools: composer:v1
          coverage: xdebug
          extensions: bcmath, gd

      - name: Install Composer dependencies
        run: composer install

      - name: Install Magento 2.4.0
        if: matrix.magento-versions == '2.4.0'
        run: |
          composer remove --no-update magento/framework magento/module-backend magento/module-customer magento/module-store magento/module-ui
          composer require magento/framework:103.0.0 magento/module-backend:102.0.0 magento/module-customer:103.0.0 magento/module-store:101.1.0 magento/module-ui:101.2.0

      - name: Install Magento 2.4.1
        if: matrix.magento-versions == '2.4.1'
        run: |
          composer remove --no-update magento/framework magento/module-backend magento/module-customer magento/module-store magento/module-ui
          composer require magento/framework:103.0.1 magento/module-backend:102.0.1 magento/module-customer:103.0.1 magento/module-store:101.1.1 magento/module-ui:101.2.1

      - name: Install Magento 2.4.2
        if: matrix.magento-versions == '2.4.2'
        run: |
          composer remove --no-update magento/framework magento/module-backend magento/module-customer magento/module-store magento/module-ui
          composer require magento/framework:103.0.2 magento/module-backend:102.0.2 magento/module-customer:103.0.2 magento/module-store:101.1.2 magento/module-ui:101.2.2

      - name: Install Magento 2.4.3
        if: matrix.magento-versions == '2.4.3'
        run: |
          composer remove --no-update magento/framework magento/module-backend magento/module-customer magento/module-store magento/module-ui
          composer require magento/framework:103.0.3 magento/module-backend:102.0.3 magento/module-customer:103.0.3 magento/module-store:101.1.3 magento/module-ui:101.2.3

      - name: Install Magento 2.4.4
        if: matrix.magento-versions == '2.4.4'
        run: |
          composer remove --no-update magento/framework magento/module-backend magento/module-customer magento/module-store magento/module-ui
          composer require magento/framework:103.0.4 magento/module-backend:102.0.4 magento/module-customer:103.0.4 magento/module-store:101.1.4 magento/module-ui:101.2.4

      - name: Install Magento 2.4.5
        if: matrix.magento-versions == '2.4.5'
        run: |
          composer remove --no-update magento/framework magento/module-backend magento/module-customer magento/module-store magento/module-ui
          composer require magento/framework:103.0.5 magento/module-backend:102.0.5 magento/module-customer:103.0.5 magento/module-store:101.1.5 magento/module-ui:101.2.5

      - name: Codesniffer
        run: composer cs-check

      - name: Static code analysis
        if: matrix.coveralls == true
        run: composer analyze

      - name: Unittests
        if: matrix.coveralls == false
        run: composer test

      - name: Unittests with coverage
        if: matrix.coveralls == true
        run: composer coverage

      - name: Coveralls report
        if: matrix.coveralls == true
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          composer require php-coveralls/php-coveralls
          ./vendor/bin/php-coveralls --coverage_clover=clover.xml -v
